spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  application:
    name: conference
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/conference
    username: user
    password: password
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
    table: flyway

server:
  port: 8081
